FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential automake libtool pkg-config libjson-c-dev libsystemd-dev libcurl3-dev

ADD . /repo
WORKDIR /repo
RUN autoreconf -if
RUN ./configure
RUN make -j8
ENV LD_LIBRARY_PATH=/repo/lib/tlog/.libs
RUN ldconfig
